// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerClient interface {
	Status(ctx context.Context, in *ControllerHealthReq, opts ...grpc.CallOption) (*ControllerHealthResp, error)
	GetRecord(ctx context.Context, in *ControllerGetRecordReq, opts ...grpc.CallOption) (*ControllerGetRecordResp, error)
	CreateRecord(ctx context.Context, in *ControllerCreateRecordReq, opts ...grpc.CallOption) (*ControllerCreateRecordResp, error)
	DeleteRecord(ctx context.Context, in *ControllerDeleteRecordReq, opts ...grpc.CallOption) (*ControllerDeleteRecordResp, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Status(ctx context.Context, in *ControllerHealthReq, opts ...grpc.CallOption) (*ControllerHealthResp, error) {
	out := new(ControllerHealthResp)
	err := c.cc.Invoke(ctx, "/api.Controller/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetRecord(ctx context.Context, in *ControllerGetRecordReq, opts ...grpc.CallOption) (*ControllerGetRecordResp, error) {
	out := new(ControllerGetRecordResp)
	err := c.cc.Invoke(ctx, "/api.Controller/GetRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) CreateRecord(ctx context.Context, in *ControllerCreateRecordReq, opts ...grpc.CallOption) (*ControllerCreateRecordResp, error) {
	out := new(ControllerCreateRecordResp)
	err := c.cc.Invoke(ctx, "/api.Controller/CreateRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DeleteRecord(ctx context.Context, in *ControllerDeleteRecordReq, opts ...grpc.CallOption) (*ControllerDeleteRecordResp, error) {
	out := new(ControllerDeleteRecordResp)
	err := c.cc.Invoke(ctx, "/api.Controller/DeleteRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility
type ControllerServer interface {
	Status(context.Context, *ControllerHealthReq) (*ControllerHealthResp, error)
	GetRecord(context.Context, *ControllerGetRecordReq) (*ControllerGetRecordResp, error)
	CreateRecord(context.Context, *ControllerCreateRecordReq) (*ControllerCreateRecordResp, error)
	DeleteRecord(context.Context, *ControllerDeleteRecordReq) (*ControllerDeleteRecordResp, error)
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (UnimplementedControllerServer) Status(context.Context, *ControllerHealthReq) (*ControllerHealthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedControllerServer) GetRecord(context.Context, *ControllerGetRecordReq) (*ControllerGetRecordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedControllerServer) CreateRecord(context.Context, *ControllerCreateRecordReq) (*ControllerCreateRecordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecord not implemented")
}
func (UnimplementedControllerServer) DeleteRecord(context.Context, *ControllerDeleteRecordReq) (*ControllerDeleteRecordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRecord not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerHealthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Controller/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Status(ctx, req.(*ControllerHealthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerGetRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Controller/GetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetRecord(ctx, req.(*ControllerGetRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_CreateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerCreateRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Controller/CreateRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateRecord(ctx, req.(*ControllerCreateRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DeleteRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerDeleteRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DeleteRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Controller/DeleteRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DeleteRecord(ctx, req.(*ControllerDeleteRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Controller_Status_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _Controller_GetRecord_Handler,
		},
		{
			MethodName: "CreateRecord",
			Handler:    _Controller_CreateRecord_Handler,
		},
		{
			MethodName: "DeleteRecord",
			Handler:    _Controller_DeleteRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
