// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: nameserver.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NameserverHealthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NameserverHealthReq) Reset() {
	*x = NameserverHealthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameserverHealthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameserverHealthReq) ProtoMessage() {}

func (x *NameserverHealthReq) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameserverHealthReq.ProtoReflect.Descriptor instead.
func (*NameserverHealthReq) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{0}
}

type NameserverHealthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *NameserverHealthResp) Reset() {
	*x = NameserverHealthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameserverHealthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameserverHealthResp) ProtoMessage() {}

func (x *NameserverHealthResp) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameserverHealthResp.ProtoReflect.Descriptor instead.
func (*NameserverHealthResp) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{1}
}

func (x *NameserverHealthResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type NameserverGetRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordKey string `protobuf:"bytes,2,opt,name=RecordKey,proto3" json:"RecordKey,omitempty"`
}

func (x *NameserverGetRecordReq) Reset() {
	*x = NameserverGetRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameserverGetRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameserverGetRecordReq) ProtoMessage() {}

func (x *NameserverGetRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameserverGetRecordReq.ProtoReflect.Descriptor instead.
func (*NameserverGetRecordReq) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{2}
}

func (x *NameserverGetRecordReq) GetRecordKey() string {
	if x != nil {
		return x.RecordKey
	}
	return ""
}

type NameserverGetRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordKey   string `protobuf:"bytes,1,opt,name=RecordKey,proto3" json:"RecordKey,omitempty"`
	RecordValue string `protobuf:"bytes,2,opt,name=RecordValue,proto3" json:"RecordValue,omitempty"`
}

func (x *NameserverGetRecordResp) Reset() {
	*x = NameserverGetRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameserverGetRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameserverGetRecordResp) ProtoMessage() {}

func (x *NameserverGetRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameserverGetRecordResp.ProtoReflect.Descriptor instead.
func (*NameserverGetRecordResp) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{3}
}

func (x *NameserverGetRecordResp) GetRecordKey() string {
	if x != nil {
		return x.RecordKey
	}
	return ""
}

func (x *NameserverGetRecordResp) GetRecordValue() string {
	if x != nil {
		return x.RecordValue
	}
	return ""
}

type NameserverCreateRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordType  string `protobuf:"bytes,1,opt,name=RecordType,proto3" json:"RecordType,omitempty"`
	RecordKey   string `protobuf:"bytes,2,opt,name=RecordKey,proto3" json:"RecordKey,omitempty"`
	RecordValue string `protobuf:"bytes,3,opt,name=RecordValue,proto3" json:"RecordValue,omitempty"`
	RecordTTL   int32  `protobuf:"varint,4,opt,name=RecordTTL,proto3" json:"RecordTTL,omitempty"`
	OverWrite   bool   `protobuf:"varint,5,opt,name=OverWrite,proto3" json:"OverWrite,omitempty"`
}

func (x *NameserverCreateRecordReq) Reset() {
	*x = NameserverCreateRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameserverCreateRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameserverCreateRecordReq) ProtoMessage() {}

func (x *NameserverCreateRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameserverCreateRecordReq.ProtoReflect.Descriptor instead.
func (*NameserverCreateRecordReq) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{4}
}

func (x *NameserverCreateRecordReq) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *NameserverCreateRecordReq) GetRecordKey() string {
	if x != nil {
		return x.RecordKey
	}
	return ""
}

func (x *NameserverCreateRecordReq) GetRecordValue() string {
	if x != nil {
		return x.RecordValue
	}
	return ""
}

func (x *NameserverCreateRecordReq) GetRecordTTL() int32 {
	if x != nil {
		return x.RecordTTL
	}
	return 0
}

func (x *NameserverCreateRecordReq) GetOverWrite() bool {
	if x != nil {
		return x.OverWrite
	}
	return false
}

type NameserverCreateRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NameserverCreateRecordResp) Reset() {
	*x = NameserverCreateRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameserverCreateRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameserverCreateRecordResp) ProtoMessage() {}

func (x *NameserverCreateRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameserverCreateRecordResp.ProtoReflect.Descriptor instead.
func (*NameserverCreateRecordResp) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{5}
}

type NameserverDeleteRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordKey string `protobuf:"bytes,2,opt,name=RecordKey,proto3" json:"RecordKey,omitempty"`
}

func (x *NameserverDeleteRecordReq) Reset() {
	*x = NameserverDeleteRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameserverDeleteRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameserverDeleteRecordReq) ProtoMessage() {}

func (x *NameserverDeleteRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameserverDeleteRecordReq.ProtoReflect.Descriptor instead.
func (*NameserverDeleteRecordReq) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{6}
}

func (x *NameserverDeleteRecordReq) GetRecordKey() string {
	if x != nil {
		return x.RecordKey
	}
	return ""
}

type NameserverDeleteRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NameserverDeleteRecordResp) Reset() {
	*x = NameserverDeleteRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nameserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameserverDeleteRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameserverDeleteRecordResp) ProtoMessage() {}

func (x *NameserverDeleteRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_nameserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameserverDeleteRecordResp.ProtoReflect.Descriptor instead.
func (*NameserverDeleteRecordResp) Descriptor() ([]byte, []int) {
	return file_nameserver_proto_rawDescGZIP(), []int{7}
}

var File_nameserver_proto protoreflect.FileDescriptor

var file_nameserver_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x15, 0x0a, 0x13, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x22, 0x2e,
	0x0a, 0x14, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x36,
	0x0a, 0x16, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x4b, 0x65, 0x79, 0x22, 0x59, 0x0a, 0x17, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4b, 0x65, 0x79, 0x12,
	0x20, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0xb7, 0x01, 0x0a, 0x19, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a,
	0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x54, 0x4c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x54, 0x4c, 0x12, 0x1c, 0x0a,
	0x09, 0x4f, 0x76, 0x65, 0x72, 0x57, 0x72, 0x69, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x4f, 0x76, 0x65, 0x72, 0x57, 0x72, 0x69, 0x74, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x39, 0x0a, 0x19, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x4b, 0x65, 0x79, 0x22, 0x1c, 0x0a, 0x1a, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x32, 0xbd, 0x02, 0x0a, 0x0a, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x3f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x51, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x2d, 0x64, 0x6e, 0x73, 0x2f, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_nameserver_proto_rawDescOnce sync.Once
	file_nameserver_proto_rawDescData = file_nameserver_proto_rawDesc
)

func file_nameserver_proto_rawDescGZIP() []byte {
	file_nameserver_proto_rawDescOnce.Do(func() {
		file_nameserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_nameserver_proto_rawDescData)
	})
	return file_nameserver_proto_rawDescData
}

var file_nameserver_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_nameserver_proto_goTypes = []interface{}{
	(*NameserverHealthReq)(nil),        // 0: api.NameserverHealthReq
	(*NameserverHealthResp)(nil),       // 1: api.NameserverHealthResp
	(*NameserverGetRecordReq)(nil),     // 2: api.NameserverGetRecordReq
	(*NameserverGetRecordResp)(nil),    // 3: api.NameserverGetRecordResp
	(*NameserverCreateRecordReq)(nil),  // 4: api.NameserverCreateRecordReq
	(*NameserverCreateRecordResp)(nil), // 5: api.NameserverCreateRecordResp
	(*NameserverDeleteRecordReq)(nil),  // 6: api.NameserverDeleteRecordReq
	(*NameserverDeleteRecordResp)(nil), // 7: api.NameserverDeleteRecordResp
}
var file_nameserver_proto_depIdxs = []int32{
	0, // 0: api.Nameserver.Status:input_type -> api.NameserverHealthReq
	2, // 1: api.Nameserver.GetRecord:input_type -> api.NameserverGetRecordReq
	4, // 2: api.Nameserver.CreateRecord:input_type -> api.NameserverCreateRecordReq
	6, // 3: api.Nameserver.DeleteRecord:input_type -> api.NameserverDeleteRecordReq
	1, // 4: api.Nameserver.Status:output_type -> api.NameserverHealthResp
	3, // 5: api.Nameserver.GetRecord:output_type -> api.NameserverGetRecordResp
	5, // 6: api.Nameserver.CreateRecord:output_type -> api.NameserverCreateRecordResp
	7, // 7: api.Nameserver.DeleteRecord:output_type -> api.NameserverDeleteRecordResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nameserver_proto_init() }
func file_nameserver_proto_init() {
	if File_nameserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nameserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameserverHealthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nameserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameserverHealthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nameserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameserverGetRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nameserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameserverGetRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nameserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameserverCreateRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nameserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameserverCreateRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nameserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameserverDeleteRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nameserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameserverDeleteRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nameserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nameserver_proto_goTypes,
		DependencyIndexes: file_nameserver_proto_depIdxs,
		MessageInfos:      file_nameserver_proto_msgTypes,
	}.Build()
	File_nameserver_proto = out.File
	file_nameserver_proto_rawDesc = nil
	file_nameserver_proto_goTypes = nil
	file_nameserver_proto_depIdxs = nil
}
